server:
  port: 8092

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.107.0.83:3306/kosadb?useSSL=false&serverTimezone=UTC
    username: kosa
    password: 1004
    hikari:
      poolName: HikariPool-1
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 10000
      maxLifetime: 1800000
      connectionTimeout: 30000


mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#server:
#  port: 8092
#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://kosa701.iptime.org:50011/kosa?useSSL=false&serverTimezone=UTC
#    username: kosa
#    password: 1004
#    hikari:
#      poolName: HikariPool-1
#      maximumPoolSize: 10
#      minimumIdle: 2
#      idleTimeout: 10000
#      maxLifetime: 1800000
#      connectionTimeout: 30000
#mybatis:
#  mapper-locations: mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
# Redis 설정 추가
spring.redis:
  host: 10.107.0.122 # Redis 호스트 주소
  port: 6379 # Redis 포트
#  host: kosa701.iptime.org # Redis 호스트 주소
#  port: 50012 # Redis 포트
  # 패스워드가 필요한 경우 아래 설정을 사용
  # password: your-password